HTMLElement.prototype.wrap=function(r){this.parentNode.insertBefore(r,this);this.parentNode.removeChild(this);r.appendChild(this)};Fluid.events={registerNavbarEvent:function(){var r=jQuery("#navbar");var o=jQuery("#navbar .dropdown-menu");if(r.offset().top>0){r.removeClass("navbar-dark");o.removeClass("navbar-dark")}Fluid.utils.listenScroll(function(){r[r.offset().top>50?"addClass":"removeClass"]("top-nav-collapse");o[r.offset().top>50?"addClass":"removeClass"]("dropdown-collapse");if(r.offset().top>0){r.removeClass("navbar-dark");o.removeClass("navbar-dark")}else{r.addClass("navbar-dark");o.removeClass("navbar-dark")}});jQuery("#navbar-toggler-btn").on("click",function(){jQuery(".animated-icon").toggleClass("open");jQuery("#navbar").toggleClass("navbar-col-show")})},registerParallaxEvent:function(){var t=jQuery('#banner[parallax="true"]');if(t.length===0){return}var a=jQuery("#board");if(a.length===0){return}var r=function(){var r=jQuery(window).scrollTop()/5;var o=parseInt(a.css("margin-top"),0);var e=96+o;if(r>e){r=e}t.css({transform:"translate3d(0,"+r+"px,0)","-webkit-transform":"translate3d(0,"+r+"px,0)","-ms-transform":"translate3d(0,"+r+"px,0)","-o-transform":"translate3d(0,"+r+"px,0)"});var n=jQuery("#toc");if(n){jQuery("#toc-ctn").css({"padding-top":r+"px"})}};Fluid.utils.listenScroll(r)},registerScrollDownArrowEvent:function(){var r=jQuery(".scroll-down-bar");if(r.length===0){return}r.on("click",function(){Fluid.utils.scrollToElement("#board",-jQuery("#navbar").height())})},registerScrollTopArrowEvent:function(){var n=jQuery("#scroll-top-button");if(n.length===0){return}var t=jQuery("#board");if(t.length===0){return}var a=false;var s=false;var r=function(){var r=t[0].getClientRects()[0].right;var o=document.body.offsetWidth;var e=o-r;a=e>=50;n.css({bottom:a&&s?"20px":"-60px",right:e-64+"px"})};r();jQuery(window).resize(r);var o=t.offset().top;Fluid.utils.listenScroll(function(){var r=document.body.scrollTop+document.documentElement.scrollTop;s=r>=o;n.css({bottom:a&&s?"20px":"-60px"})});n.on("click",function(){jQuery("body,html").animate({scrollTop:0,easing:"swing"})})},registerImageLoadedEvent:function(){if(!("NProgress"in window)){return}var r=document.getElementById("banner");if(r){var o=r.style.backgroundImage;var e=o.match(/\((.*?)\)/)[1].replace(/(['"])/g,"");var n=new Image;n.onload=function(){window.NProgress&&window.NProgress.inc(.2)};n.src=e;if(n.complete){n.onload()}}var t=jQuery("main img:not([lazyload])");var a=t.length;for(const n of t){const s=n.onload;n.onload=function(){s&&s();window.NProgress&&window.NProgress.inc(.5/a)};if(n.complete){n.onload()}}},billboard:function(){if(!("console"in window)){return}console.log(`
------------------------------------------------
|                                              |
|     ________  __            _        __      |
|    |_   __  |[  |          (_)      |  ]     |
|      | |_ \\_| | | __   _   __   .--.| |      |
|      |  _|    | |[  | | | [  |/ /'\`\\' |      |
|     _| |_     | | | \\_/ |, | || \\__/  |      |
|    |_____|   [___]'.__.'_/[___]'.__.;__]     |
|                                              |
|           Powered by Hexo x Fluid            |
|         GitHub: https://git.io/JqpVD         |
|                                              |
------------------------------------------------
    `)}};